services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: room-dashboard-v1
    image: 'roomdashboard:1.0.0'
    environment:
      - FRONT_END_PORT=9091
    ports:
      - "9091:3000"
